-- ============================================================
-- seeds/quiz_redesign_part2.sql
-- 퀴즈 시스템 시드 2단계 — quiz_question + quiz_templates
--
-- 실행 전제:
--   1) 마이그레이션 20260408000001_quiz_redesign.sql 적용 완료
--   2) seeds/quiz_redesign.sql 실행 완료 (quiz_category, drug_master)
--
-- 이 파일은 quiz_question 50건 + quiz_templates 32건 INSERT.
-- 멱등성: 시작에 DELETE 가 있어 여러 번 실행 가능.
-- ============================================================

-- ============================================================
-- 3. quiz_question (정적 문제 50건)
--
-- 챕터 분배: CH01~CH12 골고루
-- 유형 분배:
--   multiple_choice 18 / numeric 6 / true_false 4 / matching 8
--   ordering 4 / fill_blank 4 / error_spot 3 / multi_step 3
-- ============================================================
DELETE FROM quiz_question;

INSERT INTO quiz_question
  (chapter, difficulty, question_type, question, choices, correct_answer, explanation, tags, payload, hints, code_glossary, drug_refs)
VALUES

-- ─────────────────────────────────────────────────────────────
-- CH01 기본 계산 (4문제)
-- ─────────────────────────────────────────────────────────────
('CH01', 1, 'multiple_choice',
 '약품금액 계산의 기본 공식으로 올바른 것은?',
 '["단가 × 1일투여횟수 × 총투여일수","단가 × 1회투약량 × 총투여일수","단가 × 1회투약량 × 1일투여횟수 × 총투여일수","단가 × 투여총량"]'::jsonb,
 '2',
 '약품금액 = 단가(PD_PRICE) × 1회투약량(PD_DOSE) × 1일투여횟수(PD_DNUM) × 총투여일수(PD_DDAY). 원미만은 4사5입(반올림) 후 합산합니다. 4개 소스(비즈팜·공단·유팜·EDB) 모두 동일 공식을 사용합니다.',
 ARRAY['약품금액','계산공식','CH01'],
 NULL,
 '["곱셈 4개의 항으로 구성됩니다","사사오입은 약품 단위로 적용 후 합산합니다"]'::jsonb,
 '[{"code":"PD_DOSE","name":"1회 투약량"},{"code":"PD_DNUM","name":"1일 투여횟수"},{"code":"PD_DDAY","name":"총 투여일수"},{"code":"PD_PRICE","name":"단가"}]'::jsonb,
 NULL),

('CH01', 1, 'multiple_choice',
 'HIRA 청구 항번호 01이 의미하는 것은?',
 '["조제료","약품비","가산","기본진료료"]'::jsonb,
 '1',
 'HIRA 항번호는 01=약품비, 02=조제료, 03~04=가산/특수 등으로 구분됩니다. 약품금액 합계는 항 01로 집계되어 명세서 총액1을 구성합니다.',
 ARRAY['HIRA','항번호','CH01'],
 NULL,
 '["항번호는 명세서 행 구분자입니다","약품 관련 항이 가장 앞쪽에 위치합니다"]'::jsonb,
 NULL,
 NULL),

('CH01', 1, 'true_false',
 '약품금액의 사사오입은 모든 약품을 합산한 뒤 한 번만 적용한다. (O/X)',
 '["O","X"]'::jsonb,
 '1',
 'X. 사사오입은 각 약품 단위로 먼저 적용한 뒤 합산합니다. 합산 후 한 번만 적용하면 누적 오차가 발생할 수 있습니다.',
 ARRAY['사사오입','계산순서','CH01'],
 NULL,
 '["계산 순서가 결과값에 영향을 줍니다","약품별로 따로 계산 후 합산이 정답입니다"]'::jsonb,
 NULL,
 NULL),

('CH01', 2, 'matching',
 '약품금액 = 단가 × 1회투약량 × 1일투여횟수 × 총투여일수. 각 변수의 의미를 매칭하세요.',
 NULL,
 '{"l1":"r1","l2":"r2","l3":"r3","l4":"r4"}',
 '단가는 1정/캡슐 단위가격, 1회투약량은 한 번 복용량, 1일투여횟수는 하루 복용 횟수, 총투여일수는 처방 기간(일).',
 ARRAY['공식','매칭','CH01'],
 '{"left":[{"id":"l1","label":"단가"},{"id":"l2","label":"1회투약량"},{"id":"l3","label":"1일투여횟수"},{"id":"l4","label":"총투여일수"}],"right":[{"id":"r1","label":"약품 1정/캡슐의 단위가격"},{"id":"r2","label":"한 번 복용 시 정량"},{"id":"r3","label":"하루 복용 횟수"},{"id":"r4","label":"처방 기간(일)"}]}'::jsonb,
 '["곱셈의 4개 항목","단가/투약량/횟수/일수"]'::jsonb,
 NULL,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH02 약품금액 산출 (5문제)
-- ─────────────────────────────────────────────────────────────
('CH02', 1, 'numeric',
 '단가 100원, 1회 1정, 1일 3회, 5일치 처방의 약품금액은? (원, 정수)',
 NULL,
 '1500',
 '100 × 1 × 3 × 5 = 1,500원. 모든 항이 정수이므로 사사오입은 적용되지 않습니다.',
 ARRAY['약품금액','계산','CH02','easy'],
 NULL,
 '["단순 곱셈 4개 항","사사오입 필요 없는 단순 케이스"]'::jsonb,
 NULL,
 NULL),

('CH02', 2, 'numeric',
 '단가 300원, 1회 0.5정, 1일 3회, 7일치 약품 1건의 약품금액은? (원, 정수)',
 NULL,
 '3150',
 '300 × 0.5 × 3 × 7 = 3,150원. 0.5는 분할 투여(반정)를 의미합니다.',
 ARRAY['약품금액','분할투여','CH02'],
 NULL,
 '["1회 0.5정은 반정 분할 투여","순서대로 곱하기"]'::jsonb,
 NULL,
 NULL),

('CH02', 2, 'multiple_choice',
 '약품금액 계산 시 사사오입(반올림)은 어느 시점에 적용되는가?',
 '["곱셈 시작 전","각 약품의 곱셈 결과에 적용","모든 약품 합산 후 한 번만","사사오입 안 함"]'::jsonb,
 '1',
 '각 약품의 (단가×투약량×횟수×일수) 결과를 원미만 사사오입한 뒤 약품 간 합산합니다. 합산 후 일괄 처리가 아닙니다.',
 ARRAY['사사오입','적용시점','CH02'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH02', 1, 'multiple_choice',
 'DrugItem의 PD_DOSE 필드가 저장하는 값은?',
 '["1회 투약량","1일 투여횟수","총 투여일수","약품 단가"]'::jsonb,
 '0',
 'PD_DOSE는 1회 투약량(소수 4자리까지)을 저장합니다. 1일 투여횟수는 PD_DNUM, 총 투여일수는 PD_DDAY, 단가는 PD_PRICE.',
 ARRAY['DrugItem','필드정의','CH02','CH09'],
 NULL,
 NULL,
 '[{"code":"PD_DOSE","name":"1회 투약량"},{"code":"PD_DNUM","name":"1일 투여횟수"},{"code":"PD_DDAY","name":"총 투여일수"},{"code":"PD_PRICE","name":"단가"}]'::jsonb,
 NULL),

('CH02', 3, 'multi_step',
 '다음 처방의 약품금액 계산을 단계별로 채우세요. 약품A: 단가 200원, 1회 1정, 1일 3회, 5일치 / 약품B: 단가 350원, 1회 0.5정, 1일 2회, 7일치',
 NULL,
 '{"step1":3000,"step2":2450,"step3":5450}',
 '약품A = 200×1×3×5 = 3,000원. 약품B = 350×0.5×2×7 = 2,450원. 합계 = 3,000 + 2,450 = 5,450원.',
 ARRAY['약품금액','다단계','CH02'],
 '{"steps":[{"id":"step1","label":"약품A 약품금액"},{"id":"step2","label":"약품B 약품금액"},{"id":"step3","label":"합계"}]}'::jsonb,
 '["약품별로 따로 계산","마지막에 단순 합산"]'::jsonb,
 NULL,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH03 조제료 (4문제)
-- ─────────────────────────────────────────────────────────────
('CH03', 1, 'matching',
 '다음 Z코드를 해당 조제료 항목과 짝지으세요.',
 NULL,
 '{"l1":"r3","l2":"r1","l3":"r4","l4":"r2"}',
 'Z1000=약국관리료(고정), Z2000=조제기본료(기본), Z3000=복약지도료(고정), Z4xxx=조제료(일수·품목수 기반). 이 네 항목이 조제료(02항) 총액을 구성합니다.',
 ARRAY['Z코드','매칭','조제료','CH03'],
 '{"left":[{"id":"l1","label":"Z1000"},{"id":"l2","label":"Z2000"},{"id":"l3","label":"Z3000"},{"id":"l4","label":"Z4000"}],"right":[{"id":"r1","label":"조제기본료"},{"id":"r2","label":"조제료(일수별)"},{"id":"r3","label":"약국관리료"},{"id":"r4","label":"복약지도료"}]}'::jsonb,
 '["조제료 총액 = Z1000 + Z2000 + Z3000 + Z4xxx","Z1000은 약국 관리에 대한 고정 수가","Z4xxx는 일수 구간으로 세분화"]'::jsonb,
 '[{"code":"Z1000","name":"약국관리료","note":"고정"},{"code":"Z2000","name":"조제기본료","note":"기본"},{"code":"Z3000","name":"복약지도료","note":"고정"},{"code":"Z4000","name":"조제료","note":"일수·품목수 기반"}]'::jsonb,
 NULL),

('CH03', 2, 'multiple_choice',
 '조제기본료(Z2000)에 대한 설명으로 옳은 것은?',
 '["1일치 조제마다 별도 산정","처방전 1건당 1회 산정","품목 수에 비례 가산","급여 환자만 적용"]'::jsonb,
 '1',
 'Z2000 조제기본료는 처방전 1건당 1회 정액으로 산정됩니다. 일수나 품목 수에 비례하지 않으며, 급여/비급여 모두 적용됩니다.',
 ARRAY['조제기본료','Z2000','CH03'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH03', 2, 'true_false',
 '복약지도료(Z3000)는 처방 일수에 비례해 산정한다. (O/X)',
 '["O","X"]'::jsonb,
 '1',
 'X. Z3000 복약지도료는 처방전 1건당 정액(고정 수가)이며 일수와 무관합니다.',
 ARRAY['복약지도료','Z3000','CH03'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH03', 2, 'matching',
 '조제료(02항)를 구성하는 5개 Z코드와 그 의미를 매칭하세요.',
 NULL,
 '{"l1":"r1","l2":"r2","l3":"r3","l4":"r4","l5":"r5"}',
 'Z1000=약국관리료, Z2000=조제기본료, Z3000=복약지도료, Z4xxx=약품조제료(일수별), Z5000=의약품관리료. 02항 합계 = Z1000+Z2000+Z3000+Z4xxx+Z5000.',
 ARRAY['조제료','매칭','Z코드','CH03'],
 '{"left":[{"id":"l1","label":"Z1000"},{"id":"l2","label":"Z2000"},{"id":"l3","label":"Z3000"},{"id":"l4","label":"Z4xxx"},{"id":"l5","label":"Z5000"}],"right":[{"id":"r1","label":"약국관리료"},{"id":"r2","label":"조제기본료"},{"id":"r3","label":"복약지도료"},{"id":"r4","label":"약품조제료(일수별)"},{"id":"r5","label":"의약품관리료"}]}'::jsonb,
 '["5개 코드 (Z5000 포함)","Z4는 일수에 비례하는 별도 카테고리"]'::jsonb,
 NULL,
 NULL),

-- 신규: Z4110 정체 (튜터 오해 교정)
('CH03', 2, 'multiple_choice',
 'Z4110 코드의 정확한 의미는?',
 '["처방·내복 단독 (일수 무관 단일코드)","10일치 처방 내복약 조제료","외용약 단독 처방","내외용 동시 처방"]'::jsonb,
 '1',
 'Z411x는 일수별 개별코드 (Z4101=1일, Z4107=7일, Z4110=10일, Z4115=15일). 일수 무관 단일코드는 Z4120(외용), Z4130(주사) 등 별도 카테고리. Z4110을 "처방내복 단독"으로 외우면 안 됨. 근거: src/content/chapters/ch02-조제료코드.md:258.',
 ARRAY['Z4110','일수별','함정','CH03'],
 NULL,
 '["Z411x는 일수가 끝 두자리","일수 무관 코드는 Z412x/Z413x"]'::jsonb,
 NULL,
 NULL),

-- 신규: 19일치 함정 (Z4316 구간코드)
('CH03', 3, 'multiple_choice',
 '처방 내복약 19일치를 조제했습니다. 사용하는 Z코드는?',
 '["Z4119","Z4319","Z4316","Z4115"]'::jsonb,
 '2',
 'Z41xx 일수별 개별코드는 1~15일까지만 존재. 16일 이상은 구간 코드 사용: Z4316=16~20일 구간. Z4119/Z4319 같은 코드는 존재하지 않으며 생성 시 심사 반송 사유. 19일치는 16~20일 구간이므로 Z4316. 근거: ch02-조제료코드.md:245, 264.',
 ARRAY['Z4316','구간코드','심사반송','CH03'],
 NULL,
 '["15일까지만 개별코드","16일 이상은 구간으로 묶임"]'::jsonb,
 NULL,
 NULL),

-- 신규: Z41 vs Z42 분기
('CH03', 2, 'multiple_choice',
 '약품조제료 Z41xx 계열과 Z42xx 계열의 차이는?',
 '["Z41xx는 내복약, Z42xx는 외용약","Z41xx는 처방조제(처방전 받아 조제), Z42xx는 직접조제(처방전 없이 약사가 직접)","Z41xx는 1~15일분, Z42xx는 16일분 이상","Z41xx는 성인용, Z42xx는 소아용"]'::jsonb,
 '1',
 'Z41xx = 처방조제(처방전 기반), Z42xx = 직접조제(약사가 처방전 없이 일반약 조제). 직접조제는 D점수 체계로 1일 금액 × 투약일수로 산출되며 접미사를 사용하지 않음. 근거: ch02-조제료코드.md:58, 107, 214.',
 ARRAY['Z41','Z42','처방조제','직접조제','CH03'],
 NULL,
 '["숫자가 1이면 처방, 2면 직접","직접조제는 접미사 없음"]'::jsonb,
 NULL,
 NULL),

-- 신규: 일수 무관 단일코드 매칭
('CH03', 3, 'matching',
 '일수와 무관하게 적용되는 단일 Z코드와 그 의미를 매칭하세요. (Z411x 일수별과 다른 카테고리)',
 NULL,
 '{"l1":"r1","l2":"r2","l3":"r3","l4":"r4"}',
 'Z4120=외용약 단독(처방, 일수 무관 단일코드), Z4121=내외용 동시(처방), Z4130=주사 단독(처방, 자가투여주사제만 — 2021.11.01부터), Z4200=내복약 단독(직접조제, D점수 체계). 일수별로 코드가 갈리는 Z411x/Z43xx와 다른 별도 카테고리. 근거: ch02-조제료코드.md:24-25, 99-101, 107.',
 ARRAY['Z4120','Z4130','매칭','단일코드','CH03'],
 '{"left":[{"id":"l1","label":"Z4120"},{"id":"l2","label":"Z4121"},{"id":"l3","label":"Z4130"},{"id":"l4","label":"Z4200"}],"right":[{"id":"r1","label":"외용약 단독 (처방, 일수 무관)"},{"id":"r2","label":"내외용 동시 (처방)"},{"id":"r3","label":"주사 단독 (처방, 자가투여주사제)"},{"id":"r4","label":"내복약 단독 (직접조제)"}]}'::jsonb,
 '["Z412x/Z413x = 처방 단일코드","Z42xx = 직접조제"]'::jsonb,
 NULL,
 NULL),

-- 신규: 접미사 규칙 (Z4107030 = 토요)
('CH03', 3, 'multiple_choice',
 '청구 코드 "Z4107030" 이 의미하는 것은?',
 '["7일치 내복약 + 30% 가산","7일치 내복약 + 야간가산","7일치 내복약 + 토요가산","7일치 내복약 + 30일 구간 코드"]'::jsonb,
 '2',
 'Z4107(7일치 처방 내복약) + 접미사 030(토요가산) = Z4107030. 접미사 규칙: 010=야간, 030=토요, 050=공휴일. 직접조제 Z42xx는 접미사 사용하지 않음. 근거: ch02-조제료코드.md:43, 365, 423.',
 ARRAY['접미사','가산','Z4107','CH03'],
 NULL,
 '["Z4107은 7일치 내복","마지막 3자리가 가산코드"]'::jsonb,
 NULL,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH04 반올림·절사 (4문제)
-- ─────────────────────────────────────────────────────────────
('CH04', 1, 'multiple_choice',
 '약품금액 사사오입(반올림)의 적용 단위는?',
 '["1원 미만","10원 미만","100원 미만","적용하지 않음"]'::jsonb,
 '0',
 '약품 단위 약품금액은 원미만(1원 미만)을 4사5입(반올림)합니다. 10원 단위 절사는 별도 단계로 총액1 산출 시 적용됩니다.',
 ARRAY['사사오입','단위','CH04'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH04', 2, 'numeric',
 '12,345원을 10원 미만 절사하면? (정수)',
 NULL,
 '12340',
 '10원 미만 절사 = trunc10. 12,345 → 12,340. 사사오입이 아니라 버림(truncation).',
 ARRAY['절사','trunc10','CH04'],
 NULL,
 '["절사는 버림이지 반올림 아님","일의 자리를 0으로"]'::jsonb,
 NULL,
 NULL),

('CH04', 2, 'multiple_choice',
 '10원 미만 절사(trunc10)와 사사오입의 차이는?',
 '["둘 다 같은 결과","절사는 항상 버림, 사사오입은 반올림","절사는 반올림, 사사오입은 버림","적용 단위만 다름"]'::jsonb,
 '1',
 '절사(trunc)는 무조건 버림 — 12,345→12,340. 사사오입(round)은 5 이상 올림 — 12,345→12,350(원미만 기준). 적용 단위와 방향이 모두 다릅니다.',
 ARRAY['절사','사사오입','차이','CH04'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH04', 3, 'error_spot',
 '다음 계산 단계 중 잘못된 항목을 고르시오. 약품금액=8,750원 / 조제료=4,030원 / 총액1=12,780원 / 본인부담금(C10 30%)=3,830원',
 NULL,
 'step4',
 '검산: 총액1 = 8,750 + 4,030 = 12,780원 ✓. 건강보험 본인부담금 = trunc100(12,780 × 0.30) = trunc100(3,834) = 3,800원이 정답인데 3,830원으로 표기됨 → 4번이 오류. 흔한 실수: trunc10(의료급여용)을 건보에 잘못 적용하면 3,830이 나옴.',
 ARRAY['오류찾기','본인부담','CH04','CH05'],
 '{"steps":[{"id":"step1","label":"약품금액","value":"8,750원"},{"id":"step2","label":"조제료","value":"4,030원"},{"id":"step3","label":"총액1","value":"12,780원"},{"id":"step4","label":"본인부담금(C10 30%)","value":"3,830원 ← 의심"}]}'::jsonb,
 '["건보 본인부담은 trunc100","3,834를 100원 단위로 버리면?"]'::jsonb,
 NULL,
 NULL),

-- 신규: 반올림 함수 7개 ↔ 한 줄 설명 매칭
('CH04', 1, 'matching',
 '계산엔진에서 사용하는 반올림 함수와 그 동작을 매칭하세요.',
 NULL,
 '{"l1":"r1","l2":"r2","l3":"r3","l4":"r4","l5":"r5","l6":"r6","l7":"r7"}',
 'Round1=원미만 사사오입, RoundN=소수 N자리 사사오입, Trunc10=10원 미만 버림, Trunc100=100원 미만 버림, Round10=10원 미만 사사오입, Ceil10=10원 미만 올림, Ceil100=100원 미만 올림. 이름 규칙: Trunc=버림 / Round=사사오입 / Ceil=올림, 뒤 숫자=단위.',
 ARRAY['반올림','함수','CH04'],
 '{"left":[{"id":"l1","label":"Round1"},{"id":"l2","label":"RoundN"},{"id":"l3","label":"Trunc10"},{"id":"l4","label":"Trunc100"},{"id":"l5","label":"Round10"},{"id":"l6","label":"Ceil10"},{"id":"l7","label":"Ceil100"}],"right":[{"id":"r1","label":"원 미만 사사오입"},{"id":"r2","label":"소수 N자리 사사오입"},{"id":"r3","label":"10원 미만 버림"},{"id":"r4","label":"100원 미만 버림"},{"id":"r5","label":"10원 미만 사사오입"},{"id":"r6","label":"10원 미만 올림"},{"id":"r7","label":"100원 미만 올림"}]}'::jsonb,
 '["Trunc=버림 / Round=사사오입 / Ceil=올림","뒤 숫자는 적용 단위"]'::jsonb,
 NULL,
 NULL),

-- 신규: 1단계 약품 1알 가격 산출 후 어떤 함수?
('CH04', 2, 'multiple_choice',
 '[1단계] 약품 1알 가격 = 단가 × 1회투약량 × 1일투여횟수 × 총투여일수. 이 결과에 적용되는 반올림 함수는?',
 '["Round1 (원미만 사사오입)","Trunc10 (10원 미만 버림)","Ceil10 (10원 미만 올림)","Round10 (10원 미만 사사오입)"]'::jsonb,
 '0',
 '1단계 약품금액 산출은 Round1(원미만 사사오입)을 적용. 예: 432.5원 → 433원. Trunc10은 마지막 총액1/본인부담금 단계에서 사용.',
 ARRAY['Round1','약품금액','단계','CH04'],
 NULL,
 '["원 단위 결과가 필요","사사오입 계열"]'::jsonb,
 NULL,
 NULL),

-- 신규: 3단계 총액1 산출 시 함수
('CH04', 2, 'multiple_choice',
 '[3단계] 요양급여비용총액1 = 약품금액 합계 + 조제료 합계. 이 결과에 적용되는 반올림 함수는?',
 '["Round1 (원미만 사사오입)","Round10 (10원 미만 사사오입)","Trunc10 (10원 미만 버림)","Ceil10 (10원 미만 올림)"]'::jsonb,
 '2',
 '총액1은 Trunc10(10원 미만 버림)을 적용. 예: 28,789원 → 28,780원. 이후 본인부담금 단계는 보험유형에 따라 Trunc100(건보) 또는 Trunc10(의료급여)으로 갈림.',
 ARRAY['Trunc10','총액1','단계','CH04'],
 NULL,
 '["10원 단위로 끊음","사사오입이 아닌 버림"]'::jsonb,
 NULL,
 NULL),

-- 신규: 끝수계산 법적 근거
('CH04', 2, 'multiple_choice',
 '약제비 계산에서 사용하는 끝수계산(원미만 사사오입 / 10원 미만 절사 등) 규정의 법적 근거 두 가지는?',
 '["약사법 + 의료법","국민건강보험법 제107조 + 국고금관리법 제47조","건강보험심사평가원 고시 + 보건복지부 훈령","자동차손해배상보장법 + 산업재해보상보험법"]'::jsonb,
 '1',
 '끝수계산(반올림/절사) 규정의 법적 근거: 국민건강보험법 제107조 + 국고금관리법 제47조. 두 법령이 함께 작용해 "원미만 사사오입, 10원/100원 미만 절사" 같은 단위 규칙을 정의함. 근거: src/content/lessons/lesson-08-rounding-precision.md.',
 ARRAY['법령','끝수계산','CH04'],
 NULL,
 '["국민건강보험법 + 국고금관리법","두 법령이 함께"]'::jsonb,
 NULL,
 NULL),

-- 신규: 2단계 조제료 단가 → Round10
('CH04', 2, 'multiple_choice',
 '[2단계] 조제료 단가 = 점수 × 점수당단가(105.5원). 이 결과에 적용되는 반올림 함수는?',
 '["Round1 (원미만 사사오입)","Round10 (10원미만 사사오입)","Trunc10 (10원미만 버림)","Trunc100 (100원미만 버림)"]'::jsonb,
 '1',
 '조제료 단가는 Round10(10원미만 사사오입). 예: 16.20점 × 105.5 = 1,710.9원 → 1,710원. 약품금액(Round1)과 다르고, 총액1(Trunc10)과도 다름. 근거: src/lib/calc-engine/rounding.ts:42, lesson-08:99.',
 ARRAY['Round10','조제료단가','단계','CH04'],
 NULL,
 '["10원 단위 사사오입","버림이 아닌 반올림"]'::jsonb,
 NULL,
 NULL),

-- 신규: 4단계 건강보험 본인부담 → Trunc100
('CH04', 2, 'multiple_choice',
 '[4단계] 건강보험(C10) 환자의 본인부담금 = 총액1 × 본인부담률. 이 결과에 적용되는 반올림 함수는?',
 '["Round1 (원미만 사사오입)","Trunc10 (10원미만 버림)","Trunc100 (100원미만 버림)","Round100 (100원미만 사사오입)"]'::jsonb,
 '2',
 '건강보험 본인부담금은 Trunc100(100원미만 절사). 예: 4,572원 → 4,500원. 환자가 가능한 적게 내도록 100원 단위로 버림. 의료급여는 다르게 Trunc10 사용. 근거: copayment.ts (calcCopayment C타입 분기), rounding.ts:32.',
 ARRAY['Trunc100','본인부담','건강보험','단계','CH04'],
 NULL,
 '["100원 단위로 버림","환자 부담 최소화"]'::jsonb,
 NULL,
 NULL),

-- 신규: 4단계 의료급여 본인부담 → Trunc10
('CH04', 3, 'multiple_choice',
 '[4단계 — 보험유형 차이] 의료급여(D계열) 환자의 본인부담금에 적용되는 반올림 함수는?',
 '["Trunc100 (100원미만 버림) — 건강보험과 동일","Trunc10 (10원미만 버림) — 건강보험과 다름","Round10 (10원미만 사사오입)","Round1 (원미만 사사오입)"]'::jsonb,
 '1',
 '의료급여는 Trunc10(10원미만 절사). 건강보험(Trunc100)보다 더 작은 단위로 버려서 취약계층 부담을 더 줄임. 같은 "본인부담금" 단계여도 보험유형에 따라 함수가 다르다는 점이 핵심. 근거: lesson-08:78,102, rounding.ts:23.',
 ARRAY['Trunc10','의료급여','D계열','단계','CH04'],
 NULL,
 '["의료급여는 더 작은 단위로 버림","취약계층 부담 최소화"]'::jsonb,
 NULL,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH05 본인부담금 (5문제)
-- ─────────────────────────────────────────────────────────────
('CH05', 1, 'multiple_choice',
 '건강보험 일반(C10) 환자의 외래 약국 본인부담률은?',
 '["10%","20%","30%","50%"]'::jsonb,
 '2',
 'C10 건강보험 일반 외래 약국의 본인부담률은 30%입니다. 본인부담금 = trunc100(총액1 × 0.30). (의료급여 D계열은 trunc10으로 다름)',
 ARRAY['본인부담률','C10','CH05','CH06'],
 NULL,
 '["가장 일반적인 본인부담률","총액의 30%"]'::jsonb,
 '[{"code":"C10","name":"건강보험 일반","note":"본인부담률 30%"}]'::jsonb,
 NULL),

('CH05', 2, 'matching',
 '다음 보험 코드를 해당 본인부담률(또는 정액 구분)과 짝지으세요.',
 NULL,
 '{"l1":"r4","l2":"r1","l3":"r2","l4":"r3"}',
 'C10=일반 건강보험 30%, D10=의료급여 1종(저부담 정액), G10=차상위 14%, V10(또는 보훈 G계열)=10% 수준. 실제 계산엔진은 이 코드별 비율을 참조해 본인부담금을 산출합니다.',
 ARRAY['보험코드','매칭','본인부담','CH05','CH06'],
 '{"left":[{"id":"l1","label":"C10 (건강보험 일반)"},{"id":"l2","label":"D10 (의료급여 1종)"},{"id":"l3","label":"G10 (차상위)"},{"id":"l4","label":"V10 (보훈 감면)"}],"right":[{"id":"r1","label":"저부담(정액)"},{"id":"r2","label":"14%"},{"id":"r3","label":"10%"},{"id":"r4","label":"30%"}]}'::jsonb,
 '["C10이 가장 흔한 일반 건강보험","V10 보훈은 감면율이 가장 높음","D10 1종은 정액 / 저부담"]'::jsonb,
 '[{"code":"C10","name":"건강보험 일반","note":"30%"},{"code":"D10","name":"의료급여 1종","note":"정액/저부담"},{"code":"G10","name":"차상위","note":"14%"},{"code":"V10","name":"보훈","note":"10% 수준"}]'::jsonb,
 NULL),

('CH05', 2, 'numeric',
 '총액1이 16,370원인 건강보험(C10) 환자의 본인부담금은? (원, 정수)',
 NULL,
 '4910',
 '16,370 × 0.30 = 4,911 → trunc10(4,911) = 4,910원. 본인부담금은 항상 10원 단위로 절사합니다.',
 ARRAY['본인부담','계산','C10','CH05'],
 NULL,
 '["곱셈 후 trunc10 적용","본인부담률 30% = 0.30"]'::jsonb,
 NULL,
 NULL),

('CH05', 2, 'multi_step',
 '단가 300원 1정 1일 3회 5일치 약품 1종 처방, 조제료 합계 4,030원, 건강보험(C10) 환자. 단계별로 계산하세요.',
 NULL,
 '{"step1":4500,"step2":4030,"step3":8530,"step4":2500}',
 '(1) 약품금액 = 300×1×3×5 = 4,500원. (2) 조제료 = 4,030원. (3) 총액1 = 4,500+4,030 = 8,530원(10원 단위라 trunc10 무관). (4) 본인부담금 = trunc100(8,530×0.30) = trunc100(2,559) = 2,500원. (건강보험은 trunc100, 의료급여는 trunc10)',
 ARRAY['multi-step','본인부담','C10','CH05','CH12'],
 '{"steps":[{"id":"step1","label":"약품금액"},{"id":"step2","label":"조제료"},{"id":"step3","label":"총액1"},{"id":"step4","label":"본인부담금"}]}'::jsonb,
 '["각 단계 정수로 입력","건보 본인부담은 trunc100"]'::jsonb,
 NULL,
 NULL),

('CH05', 3, 'error_spot',
 '건강보험 외래 환자의 명세서에서 잘못 계산된 항목을 고르시오. (1)약품금액=12,000원 (2)조제료=4,030원 (3)총액1=16,030원 (4)본인부담금(30%)=4,810원',
 NULL,
 'step4',
 '본인부담금 = trunc100(16,030 × 0.30) = trunc100(4,809) = 4,800원이어야 합니다. 4,810원은 잘못된 값입니다. (건보는 trunc100, 의료급여는 trunc10)',
 ARRAY['오류찾기','본인부담','CH05'],
 '{"steps":[{"id":"step1","label":"약품금액","value":"12,000원"},{"id":"step2","label":"조제료","value":"4,030원"},{"id":"step3","label":"총액1","value":"16,030원"},{"id":"step4","label":"본인부담금(30%)","value":"4,810원"}]}'::jsonb,
 '["각 단계를 검산하세요","건보 본인부담은 100원 단위 절사"]'::jsonb,
 NULL,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH06 보험 유형 (4문제)
-- ─────────────────────────────────────────────────────────────
('CH06', 1, 'multiple_choice',
 '보험 코드 C10이 의미하는 것은?',
 '["건강보험 일반","의료급여 1종","의료급여 2종","산재보험"]'::jsonb,
 '0',
 'C10은 일반 건강보험(공상등구분 C 계열)입니다. 외래 약국 본인부담률 30% 적용.',
 ARRAY['C10','보험코드','CH06'],
 NULL,
 NULL,
 '[{"code":"C10","name":"건강보험 일반","note":"외래 30%"}]'::jsonb,
 NULL),

('CH06', 2, 'multiple_choice',
 '의료급여 1종(D10)과 2종(D11)의 가장 큰 차이는?',
 '["적용 약품 종류","본인부담 수준","외래/입원 구분","국가/지자체"]'::jsonb,
 '1',
 'D10(1종)은 거의 무료(정액/저부담), D11(2종)은 상대적으로 일반 급여에 가까운 본인부담을 적용합니다. 적용 약품과 외래/입원은 동일.',
 ARRAY['의료급여','D10','D11','CH06'],
 NULL,
 NULL,
 '[{"code":"D10","name":"의료급여 1종"},{"code":"D11","name":"의료급여 2종"}]'::jsonb,
 NULL),

('CH06', 2, 'true_false',
 '보훈(G/V 계열) 환자는 모든 약품 처방에서 본인부담금이 0원이다. (O/X)',
 '["O","X"]'::jsonb,
 '1',
 'X. 보훈도 일정 본인부담률(예: 10% 수준)이 적용되며 0원이 아닙니다. 다만 일반 건강보험 대비 감면율이 큽니다.',
 ARRAY['보훈','본인부담','CH06'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH06', 2, 'matching',
 '다음 보험 코드의 명칭을 짝지으세요.',
 NULL,
 '{"l1":"r2","l2":"r1","l3":"r4","l4":"r3"}',
 'C10=건강보험 일반, D10=의료급여 1종, G10=차상위 계층, S10=산재보험. 보험코드 첫 글자가 큰 카테고리를 결정합니다.',
 ARRAY['보험코드','매칭','CH06'],
 '{"left":[{"id":"l1","label":"C10"},{"id":"l2","label":"D10"},{"id":"l3","label":"G10"},{"id":"l4","label":"S10"}],"right":[{"id":"r1","label":"의료급여 1종"},{"id":"r2","label":"건강보험 일반"},{"id":"r3","label":"산재보험"},{"id":"r4","label":"차상위 계층"}]}'::jsonb,
 '["첫 글자가 카테고리를 결정","C=건강, D=의료급여, G=차상위, S=산재"]'::jsonb,
 '[{"code":"C10","name":"건강보험 일반"},{"code":"D10","name":"의료급여 1종"},{"code":"G10","name":"차상위"},{"code":"S10","name":"산재보험"}]'::jsonb,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH07 가산 (5문제)
-- ─────────────────────────────────────────────────────────────
('CH07', 2, 'matching',
 '다음 가산을 적용 조건과 짝지으세요.',
 NULL,
 '{"l1":"r2","l2":"r4","l3":"r1","l4":"r3"}',
 '산제 가산은 처방에 가루약 1건 이상 포함 시, 야간가산은 평일 18~22시 30%, 토요가산은 토요일 전일 30%, 소아심야가산은 만 6세 미만 22~익일 09시. 소아심야와 야간은 상호배타적입니다.',
 ARRAY['가산','매칭','CH07'],
 '{"left":[{"id":"l1","label":"산제(가루약) 가산"},{"id":"l2","label":"야간가산"},{"id":"l3","label":"토요가산"},{"id":"l4","label":"소아심야가산"}],"right":[{"id":"r1","label":"토요일 전일 30%"},{"id":"r2","label":"산제 포함 시"},{"id":"r3","label":"6세 미만 22-09시"},{"id":"r4","label":"평일 18-22시 30%"}]}'::jsonb,
 '["시간/연령/제형 조건을 분리해 보세요","소아심야는 야간을 대체합니다"]'::jsonb,
 NULL,
 NULL),

('CH07', 2, 'ordering',
 '계산엔진에서 가산을 평가하는 우선순위(먼저 평가되는 순)대로 정렬하세요.',
 NULL,
 'i1,i4,i3,i2',
 '계산 엔진은 (1)산제 → (2)소아심야 → (3)토요 → (4)야간 순으로 평가합니다. 소아심야는 야간을 대체하므로 야간보다 먼저 판정해야 합니다.',
 ARRAY['가산','순서','CH07'],
 '{"items":[{"id":"i1","label":"산제(가루약) 가산"},{"id":"i2","label":"야간가산"},{"id":"i3","label":"토요가산"},{"id":"i4","label":"소아심야가산"}]}'::jsonb,
 '["야간과 상호배타적인 가산이 먼저 평가되어야 함","제형 조건이 시간 조건보다 우선"]'::jsonb,
 NULL,
 NULL),

('CH07', 2, 'multiple_choice',
 '평일 야간가산이 적용되는 시간대는?',
 '["18:00 ~ 22:00","20:00 ~ 24:00","22:00 ~ 익일 06:00","16:00 ~ 20:00"]'::jsonb,
 '0',
 '평일 야간가산은 18:00~22:00 사이 조제 시 30% 가산입니다. 22시 이후는 심야가산(별도) 영역.',
 ARRAY['야간가산','시간대','CH07'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH07', 2, 'true_false',
 '토요가산과 야간가산은 같은 처방에 동시 적용될 수 있다. (O/X)',
 '["O","X"]'::jsonb,
 '1',
 'X. 일반적으로 토요가산과 야간가산은 중복 적용되지 않으며, 가산 우선순위에 따라 하나만 적용됩니다.',
 ARRAY['가산중복','CH07'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH07', 1, 'multiple_choice',
 '산제(가루약) 가산이 적용되는 조건은?',
 '["처방 약품이 모두 가루약일 때","처방에 가루약이 1건 이상 포함될 때","6세 미만 환자일 때","의사 요청 시"]'::jsonb,
 '1',
 '산제 가산은 처방에 가루약(분쇄/혼합 포함)이 1건이라도 포함되면 적용됩니다. 모든 약품이 가루약일 필요는 없습니다.',
 ARRAY['산제가산','CH07'],
 NULL,
 NULL,
 NULL,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH08 특수 케이스 (4문제)
-- ─────────────────────────────────────────────────────────────
('CH08', 1, 'multiple_choice',
 '6세 미만 영유아 가산의 기준 연령은?',
 '["만 5세 미만","만 6세 미만","만 7세 미만","만 8세 미만"]'::jsonb,
 '1',
 '6세 미만(만 6세 미만, 즉 0~5세) 영유아는 조제료에 영유아 가산이 적용됩니다.',
 ARRAY['영유아','가산','CH08'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH08', 2, 'multiple_choice',
 '65세 이상 노인 정액 특례의 기준 총액은? (외래 약국)',
 '["10,000원 이하","12,000원 이하","15,000원 이하","20,000원 이하"]'::jsonb,
 '1',
 '65세 이상 외래 약국 노인정액제는 총액1이 일정 금액(약 12,000원) 이하일 때 정액 본인부담을 적용합니다. 그 이상은 정률제 전환.',
 ARRAY['노인정액','특례','CH08'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH08', 3, 'numeric',
 '의료급여 1종(D10) 외래 환자의 약국 본인부담금 정액은? (원, 정수)',
 NULL,
 '500',
 'D10 의료급여 1종 외래 약국은 1처방당 500원 정액 본인부담이 일반적입니다(보건복지부 고시 기준).',
 ARRAY['D10','정액','CH08'],
 NULL,
 NULL,
 '[{"code":"D10","name":"의료급여 1종","note":"외래 약국 정액 500원"}]'::jsonb,
 NULL),

('CH08', 2, 'multiple_choice',
 '의료급여 2종(D11)과 1종(D10)의 본인부담 차이는?',
 '["1종이 더 부담이 큼","2종이 더 부담이 큼","동일함","약품에 따라 다름"]'::jsonb,
 '1',
 '의료급여 1종(D10)은 거의 무료에 가까운 정액, 2종(D11)은 일반 건강보험에 가까운 정률 부담을 적용합니다. 따라서 2종이 더 부담이 큽니다.',
 ARRAY['의료급여','1종','2종','CH08'],
 NULL,
 NULL,
 NULL,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH09 데이터 모델 (5문제)
-- ─────────────────────────────────────────────────────────────
('CH09', 1, 'multiple_choice',
 'TakeType enum에서 값 0이 의미하는 것은?',
 '["내복약","외용약","주사약","산제"]'::jsonb,
 '0',
 'TakeType: 0=Internal(내복약), 1=External(외용약), 2=Injection(주사약). HIRA 목번호로는 01/02/03에 대응.',
 ARRAY['TakeType','enum','CH09'],
 NULL,
 NULL,
 '[{"code":"TakeType.Internal","name":"내복약","note":"값 0"},{"code":"TakeType.External","name":"외용약","note":"값 1"},{"code":"TakeType.Injection","name":"주사약","note":"값 2"}]'::jsonb,
 NULL),

('CH09', 2, 'multiple_choice',
 'CalcOptions 인터페이스의 표준 필드 수는?',
 '["19개","39개","44개","48개"]'::jsonb,
 '2',
 'CalcOptions는 EDB PrsBillCalcOptions의 44개 필드를 기준으로 합니다(4개 소스 BIZ/HIRA/UPH/EDB의 합집합).',
 ARRAY['CalcOptions','필드','CH09'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH09', 1, 'multiple_choice',
 'InsuPayType.NonCovered(비급여)의 HIRA 항번호는?',
 '["01","U","W","A"]'::jsonb,
 '2',
 'InsuPayType.NonCovered(비급여, 값 0)의 HIRA 항번호는 W. 01=급여, U=100% 본인부담(전액), A=50% 본인부담.',
 ARRAY['InsuPayType','enum','HIRA','CH09'],
 NULL,
 NULL,
 '[{"code":"InsuPayType.Covered","name":"급여","note":"항번호 01"},{"code":"InsuPayType.NonCovered","name":"비급여","note":"항번호 W"},{"code":"InsuPayType.FullSelf","name":"100% 본인부담","note":"항번호 U"}]'::jsonb,
 NULL),

('CH09', 2, 'matching',
 'TakeType enum 값을 의미와 짝지으세요.',
 NULL,
 '{"l1":"r1","l2":"r2","l3":"r3"}',
 'TakeType: 0=Internal(내복), 1=External(외용), 2=Injection(주사). HIRA 항번호 01/02/03에 대응합니다.',
 ARRAY['TakeType','매칭','enum','CH09'],
 '{"left":[{"id":"l1","label":"값 0"},{"id":"l2","label":"값 1"},{"id":"l3","label":"값 2"}],"right":[{"id":"r1","label":"내복약(Internal)"},{"id":"r2","label":"외용약(External)"},{"id":"r3","label":"주사약(Injection)"}]}'::jsonb,
 NULL,
 NULL,
 NULL),

('CH09', 2, 'multiple_choice',
 'ICostCalcRepository 인터페이스가 정의하는 메서드 수는?',
 '["5개","7개","9개","11개"]'::jsonb,
 '2',
 'ICostCalcRepository는 9개 메서드 — 마스터 조회 3, 약국 설정 2, 이력 조회 2, 참조 데이터 2.',
 ARRAY['Repository','ICostCalcRepository','CH09'],
 NULL,
 NULL,
 NULL,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH10 명세서 (4문제)
-- ─────────────────────────────────────────────────────────────
('CH10', 1, 'multiple_choice',
 '청구 명세서에서 항번호 01이 집계하는 항목은?',
 '["조제료","약품비","가산","기본진료료"]'::jsonb,
 '1',
 '항 01=약품비, 02=조제료, 03~04=가산/특수. 약품금액 합계가 항 01에 들어갑니다.',
 ARRAY['항번호','명세서','CH10'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH10', 2, 'matching',
 '청구 명세서 항번호와 의미를 짝지으세요.',
 NULL,
 '{"l1":"r2","l2":"r3","l3":"r1","l4":"r4"}',
 '항 1=기본진료료(조제기본/관리료 등), 2=조제료, 3=약품비, 4=가산항목. 항별 합계가 총액1을 구성합니다.',
 ARRAY['항번호','매칭','CH10'],
 '{"left":[{"id":"l1","label":"항 1"},{"id":"l2","label":"항 2"},{"id":"l3","label":"항 3"},{"id":"l4","label":"항 4"}],"right":[{"id":"r1","label":"약품비"},{"id":"r2","label":"기본진료료"},{"id":"r3","label":"조제료"},{"id":"r4","label":"가산"}]}'::jsonb,
 '["기본 → 조제료 → 약품비 → 가산 순","약품비는 단일 항"]'::jsonb,
 NULL,
 NULL),

('CH10', 2, 'multiple_choice',
 '청구 명세서 작성 시 한 환자의 한 처방을 묶는 단위는?',
 '["1일","1처방전","1주","1월"]'::jsonb,
 '1',
 '명세서는 처방전 1건 단위로 작성되며, 같은 환자라도 다른 처방전은 별개로 청구됩니다.',
 ARRAY['명세서','단위','CH10'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH10', 1, 'true_false',
 '청구 명세서의 항번호 3은 약품비를 집계한다. (O/X)',
 '["O","X"]'::jsonb,
 '0',
 'O. 항번호 3 = 약품비. 약품금액 합계가 이 행에 들어갑니다.',
 ARRAY['항번호','약품비','CH10'],
 NULL,
 NULL,
 NULL,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH11 보험 수가 (3문제)
-- ─────────────────────────────────────────────────────────────
('CH11', 1, 'multiple_choice',
 'suga_main 테이블에 저장되는 데이터는?',
 '["환자 정보","수가 코드 마스터","약품 마스터","조제 이력"]'::jsonb,
 '1',
 'suga_main은 수가 코드(건강보험 행위 수가)의 마스터 테이블입니다. 각 수가코드의 점수, 적용 시작일, 종류 등을 저장.',
 ARRAY['suga','테이블','CH11'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH11', 2, 'multiple_choice',
 'insurance_rate 테이블의 핵심 컬럼은?',
 '["수가 점수","본인부담률","환자 ID","처방 번호"]'::jsonb,
 '1',
 'insurance_rate는 보험 코드별 본인부담률을 저장합니다. 계산엔진은 환자의 보험코드로 이 테이블을 참조해 본인부담금을 산출.',
 ARRAY['insurance_rate','본인부담률','CH11'],
 NULL,
 NULL,
 NULL,
 NULL),

('CH11', 2, 'multiple_choice',
 '본인부담금 산출 공식으로 옳은 것은? (건강보험 일반 환자 기준)',
 '["round1(총액1 × 본인부담률)","trunc10(총액1 × 본인부담률)","trunc100(총액1 × 본인부담률)","trunc100(약품금액 × 본인부담률)"]'::jsonb,
 '2',
 '건강보험 본인부담금 = trunc100(총액1 × 본인부담률). 100원 미만 절사. 의료급여(D계열)는 trunc10(10원 미만 절사)로 다름. 코드 근거: src/lib/calc-engine/copayment.ts (calcCopayment 함수, C타입 분기).',
 ARRAY['본인부담','공식','trunc100','CH11'],
 NULL,
 '["100원 미만 버림","건강보험은 100원 단위, 의료급여는 10원 단위"]'::jsonb,
 NULL,
 NULL),

-- 신규: 약제비 관련 5개 법령 ↔ 적용 주제 매칭
('CH11', 3, 'matching',
 '약제비 계산과 관련된 주요 법령/규정을 적용 주제와 매칭하세요.',
 NULL,
 '{"l1":"r1","l2":"r2","l3":"r3","l4":"r4","l5":"r5"}',
 '국민건강보험법 제107조=끝수계산 규정 / 국민건강보험법 시행령 별표2=건강보험 종별 본인부담률 / 의료급여법 시행령 별표1=의료급여 본인부담 / 자동차손해배상보장법=자동차보험(F계열) 환자 본인부담 면제 / 국가보훈대상자 의료지원에 관한 규칙=보훈(G계열) 환자 본인부담.',
 ARRAY['법령','매칭','CH11'],
 '{"left":[{"id":"l1","label":"국민건강보험법 제107조"},{"id":"l2","label":"국민건강보험법 시행령 별표2"},{"id":"l3","label":"의료급여법 시행령 별표1"},{"id":"l4","label":"자동차손해배상보장법"},{"id":"l5","label":"국가보훈대상자 의료지원에 관한 규칙"}],"right":[{"id":"r1","label":"끝수계산(반올림/절사) 규정"},{"id":"r2","label":"건강보험(C계열) 종별 본인부담률"},{"id":"r3","label":"의료급여(D계열) 본인부담 기준"},{"id":"r4","label":"자동차보험(F계열) 환자 본인부담 면제"},{"id":"r5","label":"보훈(G계열) 환자 본인부담 산정"}]}'::jsonb,
 '["보험 종별 = 시행령 별표","자보는 손해배상보장법"]'::jsonb,
 NULL,
 NULL),

-- ─────────────────────────────────────────────────────────────
-- CH12 통합 시나리오 (4문제)
-- ─────────────────────────────────────────────────────────────
('CH12', 3, 'ordering',
 '계산엔진의 처방전 처리 순서를 올바르게 정렬하세요.',
 NULL,
 'i1,i2,i3,i4,i5',
 '(1)약품금액 산출 → (2)조제료 산출 → (3)가산 평가/적용 → (4)총액1 산출(trunc10) → (5)본인부담금 산출 — 건강보험은 trunc100, 의료급여는 trunc10. 가산은 조제료 단계에 흡수되어 총액 산출 전에 마무리됩니다.',
 ARRAY['계산순서','통합','CH12'],
 '{"items":[{"id":"i1","label":"약품금액 산출"},{"id":"i2","label":"조제료 산출"},{"id":"i3","label":"가산 평가/적용"},{"id":"i4","label":"총액1 산출"},{"id":"i5","label":"본인부담금 산출"}]}'::jsonb,
 '["약품 → 조제료 → 가산 → 총액 → 본인부담","총액과 본인부담금은 마지막 두 단계"]'::jsonb,
 NULL,
 NULL),

('CH12', 3, 'multi_step',
 '복합 처방: 약품A(단가 200원, 1정, 1일3회, 5일치) + 약품B(단가 350원, 0.5정, 1일2회, 7일치). 조제료 합계 4,300원. 건강보험 일반(C10) 환자. 단계별로 채우세요.',
 NULL,
 '{"step1":3000,"step2":2450,"step3":5450,"step4":4300,"step5":9750,"step6":2900}',
 '약품A=200×1×3×5=3,000. 약품B=350×0.5×2×7=2,450. 약품금액 합계=5,450. 조제료=4,300. 총액1=trunc10(5,450+4,300)=9,750. 본인부담=trunc100(9,750×0.30)=trunc100(2,925)=2,900. (건강보험은 trunc100, 의료급여는 trunc10)',
 ARRAY['multi-step','통합','C10','CH12'],
 '{"steps":[{"id":"step1","label":"약품A 약품금액"},{"id":"step2","label":"약품B 약품금액"},{"id":"step3","label":"약품금액 합계"},{"id":"step4","label":"조제료 합계"},{"id":"step5","label":"총액1"},{"id":"step6","label":"본인부담금"}]}'::jsonb,
 '["약품별로 따로 계산","총액1은 trunc10, 건보 본인부담은 trunc100"]'::jsonb,
 NULL,
 NULL),

('CH12', 3, 'error_spot',
 '다음 명세서에서 잘못 계산된 항목을 고르시오. (1)약품금액 합계 8,200원 (2)조제료 합계 4,030원 (3)총액1 12,230원 (4)본인부담금(C10 30%) 3,660원',
 NULL,
 'step4',
 '검산: 총액1 = 8,200 + 4,030 = 12,230원 ✓. 건강보험 본인부담금 = trunc100(12,230 × 0.30) = trunc100(3,669) = 3,600원이 정답인데 3,660원으로 표기됨 → 4번이 오류. 흔한 실수: trunc10을 잘못 적용하면 3,660이 나옴(의료급여용 함수).',
 ARRAY['오류찾기','통합','CH12'],
 '{"steps":[{"id":"step1","label":"약품금액 합계","value":"8,200원"},{"id":"step2","label":"조제료 합계","value":"4,030원"},{"id":"step3","label":"총액1","value":"12,230원"},{"id":"step4","label":"본인부담금(C10 30%)","value":"3,660원 ← 의심"}]}'::jsonb,
 '["건보 본인부담은 trunc100","3,669를 100원 단위로 버리면?"]'::jsonb,
 NULL,
 NULL),

('CH12', 3, 'multiple_choice',
 '복합 처방 (약품A 300원×1정×1일2회×5일, 약품B 500원×1정×1일3회×7일)의 약품금액 합계는?',
 '["13,500원","12,000원","13,000원","14,500원"]'::jsonb,
 '0',
 '약품A = 300×1×2×5 = 3,000원. 약품B = 500×1×3×7 = 10,500원. 합계 = 13,500원.',
 ARRAY['통합','약품금액','CH12'],
 NULL,
 '["약품별로 계산 후 합산","사사오입 필요 없는 정수 곱셈"]'::jsonb,
 NULL,
 NULL);


-- ============================================================
-- 4. quiz_templates  (동적 템플릿 32건 — 시나리오 기반)
--
-- 시나리오 × 난이도 × 유형 매트릭스:
--   성인 감기 (cold_adult)        : L1×3, L2×2
--   소아 감기 (cold_pediatric)    : L2×3
--   소아 항생제 (pediatric_uri_abx): L2×2
--   고혈압 단일 (hypertension_mono): L2×3, L3×2
--   고혈압 복합 (hypertension_combo): L3×2
--   당뇨 (diabetes_t2)            : L2×2
--   고혈압+당뇨 (htn_dm_combo)    : L3×3
--   위염 (gerd_acute)             : L1×2
--   만성통증 (chronic_pain)       : L2×2
--   노인 다약제 (elderly)         : L3×3
--   소아 비염 (pediatric_ent)     : L2×1
-- ============================================================
DELETE FROM quiz_templates;

INSERT INTO quiz_templates
  (template_type, difficulty, scenario_label, insu_code_pool, param_schema, prompt_template, answer_field, hint_template, drug_pool_filter, enabled)
VALUES

-- ── 성인 감기 (5) ──────────────────────────────────────────────
('calc-drug-amount', 1, '성인 감기 단일 처방', ARRAY['C10'],
 '{"age":{"min":20,"max":50},"drugCount":{"min":1,"max":1},"dayRange":{"min":3,"max":5},"doseChoices":[1],"dnumChoices":[3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 성인 환자 — 감기 단일 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}\n(단위: 원, 정수)',
 'drugAmount',
 '["약품금액 = 단가 × 1회투약량 × 1일횟수 × 일수","사사오입은 약품 단위로 적용 후 합산"]'::jsonb,
 '{"clinicalGroups":["cold_adult"]}'::jsonb,
 true),

('calc-copay', 1, '성인 감기 단일 처방', ARRAY['C10'],
 '{"age":{"min":20,"max":50},"drugCount":{"min":1,"max":1},"dayRange":{"min":3,"max":5},"doseChoices":[1],"dnumChoices":[3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 성인 환자 — 감기 단일 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'userPrice',
 '["건강보험 일반 본인부담률 30%","본인부담금 = trunc10(총액1 × 0.30)"]'::jsonb,
 '{"clinicalGroups":["cold_adult"]}'::jsonb,
 true),

('calc-total', 1, '성인 감기 2종 처방', ARRAY['C10'],
 '{"age":{"min":20,"max":50},"drugCount":{"min":2,"max":2},"dayRange":{"min":3,"max":5},"doseChoices":[1],"dnumChoices":[3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 성인 환자 — 감기 2종 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'totalPrice',
 '["총액1 = 약품금액(01항) + 조제료(02항)","trunc10 적용"]'::jsonb,
 '{"clinicalGroups":["cold_adult"]}'::jsonb,
 true),

('calc-copay', 2, '성인 감기 복합 처방', ARRAY['C10'],
 '{"age":{"min":20,"max":50},"drugCount":{"min":2,"max":3},"dayRange":{"min":3,"max":7},"doseChoices":[1],"dnumChoices":[3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 성인 환자 — 감기 복합 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'userPrice',
 '["여러 약품의 약품금액을 각각 계산 후 합산","본인부담금은 trunc10 적용"]'::jsonb,
 '{"clinicalGroups":["cold_adult"]}'::jsonb,
 true),

('multi-step', 2, '성인 감기 단계별 계산', ARRAY['C10'],
 '{"age":{"min":20,"max":50},"drugCount":{"min":2,"max":2},"dayRange":{"min":3,"max":5},"doseChoices":[1],"dnumChoices":[3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 성인 환자 — 감기 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n다음 4단계를 모두 계산하세요:\n(1) 약품금액 합계\n(2) 조제료 합계\n(3) 총액1\n(4) 본인부담금',
 'multiStep',
 '["각 단계를 순서대로 계산","마지막 두 단계는 trunc10 적용"]'::jsonb,
 '{"clinicalGroups":["cold_adult"]}'::jsonb,
 true),

-- ── 소아 감기 (3, 6세 미만 가산 학습) ─────────────────────────
('calc-copay', 2, '소아 감기 (영유아 가산)', ARRAY['C10'],
 '{"age":{"min":1,"max":5},"drugCount":{"min":1,"max":2},"dayRange":{"min":3,"max":5},"doseChoices":[1],"dnumChoices":[3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 소아 환자 — 감기 시럽 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}\n\n※ 6세 미만 영유아 가산이 조제료에 반영됩니다.',
 'userPrice',
 '["6세 미만 영유아는 조제료에 가산","건강보험 일반은 30% 본인부담"]'::jsonb,
 '{"clinicalGroups":["cold_pediatric"]}'::jsonb,
 true),

('calc-total', 2, '소아 감기 시럽 처방', ARRAY['C10'],
 '{"age":{"min":2,"max":11},"drugCount":{"min":2,"max":3},"dayRange":{"min":3,"max":5},"doseChoices":[1],"dnumChoices":[3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 소아 환자 — 감기 시럽 복합.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'totalPrice',
 '["시럽 단가는 정제보다 일반적으로 높음","총액1 = 약품금액 + 조제료"]'::jsonb,
 '{"clinicalGroups":["cold_pediatric"]}'::jsonb,
 true),

('multi-step', 2, '소아 감기 단계별', ARRAY['C10'],
 '{"age":{"min":3,"max":11},"drugCount":{"min":2,"max":2},"dayRange":{"min":3,"max":5},"doseChoices":[1],"dnumChoices":[3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 소아 환자 — 감기 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n다음 4단계를 모두 계산하세요:\n(1) 약품금액 합계\n(2) 조제료 합계\n(3) 총액1\n(4) 본인부담금',
 'multiStep',
 '["시럽 처방 단계별 계산","trunc10 적용 위치 주의"]'::jsonb,
 '{"clinicalGroups":["cold_pediatric"]}'::jsonb,
 true),

-- ── 소아 항생제 (2) ───────────────────────────────────────────
('calc-copay', 2, '소아 상기도 감염 항생제', ARRAY['C10'],
 '{"age":{"min":2,"max":10},"drugCount":{"min":1,"max":2},"dayRange":{"min":5,"max":7},"doseChoices":[1],"dnumChoices":[2,3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 소아 환자 — 상기도 감염 항생제 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'userPrice',
 '["항생제는 일반적으로 5~7일치 처방","소아 시럽은 단가가 비교적 높음"]'::jsonb,
 '{"clinicalGroups":["pediatric_uri_abx"]}'::jsonb,
 true),

('multi-step', 2, '소아 항생제 단계별', ARRAY['C10'],
 '{"age":{"min":3,"max":10},"drugCount":{"min":1,"max":2},"dayRange":{"min":5,"max":7},"doseChoices":[1],"dnumChoices":[2,3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 소아 환자 — 항생제 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n다음 4단계를 모두 계산하세요:\n(1) 약품금액 합계\n(2) 조제료 합계\n(3) 총액1\n(4) 본인부담금',
 'multiStep',
 '["일수가 길어질수록 약품금액 비중 커짐","마지막 두 단계 trunc10"]'::jsonb,
 '{"clinicalGroups":["pediatric_uri_abx"]}'::jsonb,
 true),

-- ── 고혈압 단일 (5, L2/L3) ────────────────────────────────────
('calc-drug-amount', 2, '고혈압 단독 만성 (28일치)', ARRAY['C10'],
 '{"age":{"min":40,"max":70},"drugCount":{"min":1,"max":1},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 고혈압 환자 — 단일제 28일 만성 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'drugAmount',
 '["만성 처방은 28~30일이 표준","단가 × 1정 × 1일1회 × 28일"]'::jsonb,
 '{"clinicalGroups":["hypertension_mono"]}'::jsonb,
 true),

('calc-total', 2, '고혈압 단독 만성', ARRAY['C10'],
 '{"age":{"min":40,"max":70},"drugCount":{"min":1,"max":1},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 고혈압 환자 — 단일제 만성 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'totalPrice',
 '["총액1 = 약품금액 + 조제료","장기처방 가산 가능"]'::jsonb,
 '{"clinicalGroups":["hypertension_mono"]}'::jsonb,
 true),

('calc-copay', 2, '고혈압 단독 만성', ARRAY['C10'],
 '{"age":{"min":40,"max":70},"drugCount":{"min":1,"max":1},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 고혈압 환자 — 단일제 만성 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'userPrice',
 '["건강보험 일반 30%","trunc10 적용"]'::jsonb,
 '{"clinicalGroups":["hypertension_mono"]}'::jsonb,
 true),

('calc-copay', 3, '고혈압 단독 (의료급여)', ARRAY['D10'],
 '{"age":{"min":40,"max":70},"drugCount":{"min":1,"max":1},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 의료급여 환자 — 고혈압 단일제.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}\n\n※ D10 의료급여 1종은 정액 본인부담을 적용합니다.',
 'userPrice',
 '["D10 의료급여 1종은 정액 부담","C10과 다른 본인부담 산식"]'::jsonb,
 '{"clinicalGroups":["hypertension_mono"]}'::jsonb,
 true),

('multi-step', 3, '고혈압 만성 단계별', ARRAY['C10'],
 '{"age":{"min":50,"max":75},"drugCount":{"min":1,"max":2},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 환자 — 고혈압 만성 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n다음 4단계를 모두 계산하세요:\n(1) 약품금액 합계\n(2) 조제료 합계\n(3) 총액1\n(4) 본인부담금',
 'multiStep',
 '["28일치 만성 처방 단계별","총액1과 본인부담 trunc10"]'::jsonb,
 '{"clinicalGroups":["hypertension_mono"]}'::jsonb,
 true),

-- ── 고혈압 복합 (2) ───────────────────────────────────────────
('calc-copay', 3, '고혈압 복합제 + 이뇨제', ARRAY['C10'],
 '{"age":{"min":50,"max":80},"drugCount":{"min":2,"max":2},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 환자 — 고혈압 복합 + 이뇨제 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'userPrice',
 '["복합제는 단가가 단일제보다 높음","이뇨제는 동반 처방으로 자주 등장"]'::jsonb,
 '{"clinicalGroups":["hypertension_combo"]}'::jsonb,
 true),

('multi-step', 3, '고혈압 복합 단계별', ARRAY['C10'],
 '{"age":{"min":50,"max":80},"drugCount":{"min":2,"max":2},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 환자 — 고혈압 복합 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n다음 4단계를 모두 계산하세요:\n(1) 약품금액 합계\n(2) 조제료 합계\n(3) 총액1\n(4) 본인부담금',
 'multiStep',
 '["약품 2종 단가 합산 주의","장기 처방 trunc10"]'::jsonb,
 '{"clinicalGroups":["hypertension_combo"]}'::jsonb,
 true),

-- ── 당뇨 (2) ──────────────────────────────────────────────────
('calc-copay', 2, '2형 당뇨 단독 처방', ARRAY['C10'],
 '{"age":{"min":40,"max":70},"drugCount":{"min":1,"max":2},"dayRange":{"min":30,"max":30},"doseChoices":[1],"dnumChoices":[1,2]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 2형 당뇨 환자.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'userPrice',
 '["메트포민은 1일 2회 표준","DPP-4i는 1일 1회"]'::jsonb,
 '{"clinicalGroups":["diabetes_t2"]}'::jsonb,
 true),

('calc-total', 2, '2형 당뇨 만성', ARRAY['C10'],
 '{"age":{"min":40,"max":70},"drugCount":{"min":1,"max":2},"dayRange":{"min":30,"max":30},"doseChoices":[1],"dnumChoices":[1,2]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 2형 당뇨 환자 — 30일 만성.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'totalPrice',
 '["30일치 처방","총액1 산출"]'::jsonb,
 '{"clinicalGroups":["diabetes_t2"]}'::jsonb,
 true),

-- ── 고혈압 + 당뇨 동반 (3) ────────────────────────────────────
('calc-copay', 3, '고혈압 + 당뇨 동반', ARRAY['C10'],
 '{"age":{"min":55,"max":80},"drugCount":{"min":2,"max":4},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1,2]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 환자 — 고혈압 + 당뇨 동반 만성 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'userPrice',
 '["만성질환 동반 처방","약품 종류와 일수 모두 확인"]'::jsonb,
 '{"clinicalGroups":["hypertension_mono","diabetes_t2","htn_dm_combo"]}'::jsonb,
 true),

('calc-total', 3, '고혈압 + 당뇨 + 스타틴', ARRAY['C10'],
 '{"age":{"min":55,"max":80},"drugCount":{"min":3,"max":4},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1,2]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 환자 — 고혈압 + 당뇨 + 이상지질혈증.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'totalPrice',
 '["3~4종 약품 합산","총액1 산출"]'::jsonb,
 '{"clinicalGroups":["hypertension_mono","diabetes_t2","htn_dm_combo"]}'::jsonb,
 true),

('multi-step', 3, '고혈압+당뇨 단계별', ARRAY['C10'],
 '{"age":{"min":55,"max":80},"drugCount":{"min":2,"max":3},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 환자 — 고혈압 + 당뇨 동반 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n다음 4단계를 모두 계산하세요:\n(1) 약품금액 합계\n(2) 조제료 합계\n(3) 총액1\n(4) 본인부담금',
 'multiStep',
 '["복수 만성질환 다약제","각 단계 trunc10 적용 위치 확인"]'::jsonb,
 '{"clinicalGroups":["hypertension_mono","diabetes_t2"]}'::jsonb,
 true),

-- ── 위염 / 역류 (2) ───────────────────────────────────────────
('calc-drug-amount', 1, '위염 단기 처방', ARRAY['C10'],
 '{"age":{"min":20,"max":60},"drugCount":{"min":1,"max":2},"dayRange":{"min":7,"max":14},"doseChoices":[1],"dnumChoices":[1,2,3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 환자 — 위염/역류 단기 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'drugAmount',
 '["PPI는 1일 1회 식전","점막보호제는 1일 3회"]'::jsonb,
 '{"clinicalGroups":["gerd_acute"]}'::jsonb,
 true),

('calc-copay', 1, '위염 단기 처방', ARRAY['C10'],
 '{"age":{"min":20,"max":60},"drugCount":{"min":1,"max":2},"dayRange":{"min":7,"max":14},"doseChoices":[1],"dnumChoices":[1,2,3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 환자 — 위염 단기 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'userPrice',
 '["단기 처방의 본인부담","trunc10 적용"]'::jsonb,
 '{"clinicalGroups":["gerd_acute"]}'::jsonb,
 true),

-- ── 만성 통증 (2) ─────────────────────────────────────────────
('calc-copay', 2, '만성 통증 NSAID', ARRAY['C10'],
 '{"age":{"min":40,"max":75},"drugCount":{"min":1,"max":2},"dayRange":{"min":14,"max":30},"doseChoices":[1],"dnumChoices":[1,2,3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 환자 — 만성 통증 NSAID 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'userPrice',
 '["NSAID는 1일 1~3회","COX-2 선택약은 1일 1회"]'::jsonb,
 '{"clinicalGroups":["chronic_pain"]}'::jsonb,
 true),

('calc-total', 2, '만성 통증 (위장보호 동반)', ARRAY['C10'],
 '{"age":{"min":40,"max":75},"drugCount":{"min":2,"max":2},"dayRange":{"min":14,"max":30},"doseChoices":[1],"dnumChoices":[1,2]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 환자 — 만성 통증 + 위장보호.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'totalPrice',
 '["NSAID 장기 처방 시 위장보호제 동반","총액1 산출"]'::jsonb,
 '{"clinicalGroups":["chronic_pain"]}'::jsonb,
 true),

-- ── 노인 다약제 (3) ───────────────────────────────────────────
('calc-copay', 3, '노인 다약제 (5종+)', ARRAY['C10'],
 '{"age":{"min":70,"max":85},"drugCount":{"min":4,"max":5},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1,2]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 노인 환자 — 다약제 만성 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}\n\n※ 65세 이상 노인 정액 특례 가능성을 검토하세요.',
 'userPrice',
 '["65세 이상 노인정액 기준 확인","총액1이 일정 금액 이하면 정액 적용"]'::jsonb,
 '{"clinicalGroups":["elderly_polypharmacy","hypertension_mono","diabetes_t2"]}'::jsonb,
 true),

('calc-total', 3, '노인 만성 다약제', ARRAY['C10'],
 '{"age":{"min":70,"max":85},"drugCount":{"min":4,"max":5},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1,2]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 노인 환자 — 다약제 만성 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'totalPrice',
 '["여러 약품의 단가 누적","총액1 = 약품금액 + 조제료"]'::jsonb,
 '{"clinicalGroups":["elderly_polypharmacy","hypertension_mono","diabetes_t2"]}'::jsonb,
 true),

('multi-step', 3, '노인 다약제 단계별', ARRAY['C10'],
 '{"age":{"min":70,"max":85},"drugCount":{"min":3,"max":4},"dayRange":{"min":28,"max":30},"doseChoices":[1],"dnumChoices":[1]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 노인 환자 — 다약제 만성 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n다음 4단계를 모두 계산하세요:\n(1) 약품금액 합계\n(2) 조제료 합계\n(3) 총액1\n(4) 본인부담금',
 'multiStep',
 '["다약제 합산 누락 주의","trunc10 적용 위치 확인"]'::jsonb,
 '{"clinicalGroups":["elderly_polypharmacy","hypertension_mono"]}'::jsonb,
 true),

-- ── 소아 비염 (1) ─────────────────────────────────────────────
('calc-copay', 2, '소아 비염 만성', ARRAY['C10'],
 '{"age":{"min":4,"max":11},"drugCount":{"min":2,"max":3},"dayRange":{"min":7,"max":14},"doseChoices":[1],"dnumChoices":[1,2,3]}'::jsonb,
 E'[{difficultyLabel}] {insuName}({insuCode}) 소아 환자 — 알레르기성 비염 처방.\n환자 나이: {ageDesc}\n처방 약품 목록:\n{drugListText}\n\n{questionText}',
 'userPrice',
 '["항히스타민제는 1일 1회","점액 용해제는 1일 3회"]'::jsonb,
 '{"clinicalGroups":["pediatric_ent"]}'::jsonb,
 true);
